plugins {
    id 'fabric-loom' version '1.7-SNAPSHOT'
    id 'maven-publish'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = mod_version
group = mod_group_id

repositories {
    mavenLocal()
    maven {
        name "KosmX's maven"
        url 'https://maven.kosmx.dev/'
        content {
            includeGroup("dev.kosmx.player-anim")
        }
    }
}

base {
    archivesName = "HugMe!-Fabric-$minecraft_version"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    modImplementation "dev.kosmx.player-anim:player-animation-lib-fabric:${player_anim_version}"
}

processResources {
    var replaceProperties = [
            minecraft_version: minecraft_version,
            loader_version   : loader_version,
            fabric_version   : fabric_version,
            mod_id           : mod_id,
            mod_name         : mod_name,
            mod_license      : mod_license,
            mod_version      : mod_version,
            mod_authors      : mod_authors,
            mod_description  : mod_description
    ]
    inputs.properties replaceProperties
    filesMatching(['fabric.mod.json']) {
        expand replaceProperties
    }
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

